-- Additive history storage. Baseline capture is an explicit, separate administrator operation.
CREATE TABLE version_baseline_runs (
 id INTEGER PRIMARY KEY CHECK(id=1),
 created_by BIGINT NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE post_versions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
 snapshot_schema_version INTEGER NOT NULL CHECK(snapshot_schema_version = 1),
 snapshot_json CLOB NOT NULL,
 reason VARCHAR(32) NOT NULL CHECK(reason IN ('BASELINE_DRAFT','BASELINE_PUBLISHED','BASELINE_TEMPLATE','MANUAL_DRAFT','PUBLISH','RESTORE_BACKUP','RESTORE')),
 source_revision BIGINT NOT NULL,
 source_version_id BIGINT,
 operation_id VARCHAR(36),
 created_by BIGINT NOT NULL,
 creator_name VARCHAR(80) NOT NULL,
 activity_log_id BIGINT REFERENCES activity_log(id) ON DELETE SET NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(post_id,operation_id,reason)
);
CREATE INDEX post_versions_target ON post_versions(post_id,id);
CREATE TABLE post_version_media (
 version_id BIGINT NOT NULL REFERENCES post_versions(id) ON DELETE CASCADE,
 media_id BIGINT NOT NULL REFERENCES media(id),
 PRIMARY KEY(version_id,media_id)
);
CREATE INDEX post_version_media_lookup ON post_version_media(media_id,version_id);
CREATE TABLE page_versions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 page_id BIGINT NOT NULL REFERENCES site_pages(id) ON DELETE CASCADE,
 snapshot_schema_version INTEGER NOT NULL CHECK(snapshot_schema_version = 1),
 snapshot_json CLOB NOT NULL,
 reason VARCHAR(32) NOT NULL CHECK(reason IN ('BASELINE_DRAFT','BASELINE_PUBLISHED','BASELINE_TEMPLATE','MANUAL_DRAFT','PUBLISH','RESTORE_BACKUP','RESTORE')),
 source_revision BIGINT NOT NULL,
 source_version_id BIGINT,
 operation_id VARCHAR(36),
 created_by BIGINT NOT NULL,
 creator_name VARCHAR(80) NOT NULL,
 activity_log_id BIGINT REFERENCES activity_log(id) ON DELETE SET NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(page_id,operation_id,reason)
);
CREATE INDEX page_versions_target ON page_versions(page_id,id);
CREATE TABLE page_version_media (
 version_id BIGINT NOT NULL REFERENCES page_versions(id) ON DELETE CASCADE,
 media_id BIGINT NOT NULL REFERENCES media(id),
 PRIMARY KEY(version_id,media_id)
);
CREATE INDEX page_version_media_lookup ON page_version_media(media_id,version_id);
CREATE TABLE page_template_versions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 template_id BIGINT NOT NULL REFERENCES page_templates(id) ON DELETE CASCADE,
 snapshot_schema_version INTEGER NOT NULL CHECK(snapshot_schema_version = 1),
 snapshot_json CLOB NOT NULL,
 reason VARCHAR(32) NOT NULL CHECK(reason IN ('BASELINE_DRAFT','BASELINE_PUBLISHED','BASELINE_TEMPLATE','MANUAL_DRAFT','PUBLISH','RESTORE_BACKUP','RESTORE')),
 source_revision BIGINT NOT NULL,
 source_version_id BIGINT,
 operation_id VARCHAR(36),
 created_by BIGINT NOT NULL,
 creator_name VARCHAR(80) NOT NULL,
 activity_log_id BIGINT REFERENCES activity_log(id) ON DELETE SET NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(template_id,operation_id,reason)
);
CREATE INDEX page_template_versions_target ON page_template_versions(template_id,id);
CREATE TABLE page_template_version_media (
 version_id BIGINT NOT NULL REFERENCES page_template_versions(id) ON DELETE CASCADE,
 media_id BIGINT NOT NULL REFERENCES media(id),
 PRIMARY KEY(version_id,media_id)
);
CREATE INDEX page_template_version_media_lookup ON page_template_version_media(media_id,version_id);

