-- Site composition. Existing pages stay PAGE areas with no content-work link and hidden from the
-- derived menu; no existing row is rewritten. Operating rules (one representative area per content
-- type, GROUP never published, depth) are service/UI rules, not constraints here.
ALTER TABLE site_pages ADD COLUMN area_kind VARCHAR(16) NOT NULL DEFAULT 'PAGE';
ALTER TABLE site_pages ADD CONSTRAINT site_pages_area_kind CHECK(area_kind IN ('PAGE','GROUP'));
ALTER TABLE site_pages ADD COLUMN content_type_code VARCHAR(32);
ALTER TABLE site_pages ADD CONSTRAINT site_pages_content_type_fk FOREIGN KEY(content_type_code) REFERENCES content_types(code);
ALTER TABLE site_pages ADD COLUMN menu_visible BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE site_pages ADD COLUMN menu_label VARCHAR(80);
-- Published site structure: a snapshot that refers to areas by page id (never by URL).
CREATE TABLE site_structure_publications (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 snapshot_json CLOB NOT NULL,
 fingerprint VARCHAR(64) NOT NULL,
 reason VARCHAR(16) NOT NULL CHECK(reason IN ('PUBLISH','REPUBLISH')),
 source_publication_id BIGINT REFERENCES site_structure_publications(id),
 published_by BIGINT NOT NULL REFERENCES users(id),
 publisher_name VARCHAR(80) NOT NULL,
 published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- Page ids each snapshot refers to. No foreign key to site_pages: an older snapshot must not block
-- deleting a page forever; only the latest snapshot protects its pages.
CREATE TABLE site_structure_publication_pages (
 publication_id BIGINT NOT NULL REFERENCES site_structure_publications(id) ON DELETE CASCADE,
 page_id BIGINT NOT NULL,
 PRIMARY KEY(publication_id,page_id)
);
CREATE INDEX site_structure_publication_page ON site_structure_publication_pages(page_id,publication_id);
