-- 콘텐츠 작업 하위 항목 (V16). A node is an operator-made sub-navigation entry under a page linked to a
-- content type: a name, an order and one topic condition. Nodes are admin navigation only: never a
-- page, never published, never part of the public structure or menus, and never derived from the
-- topic dictionary. Removing a node deletes this row only; topics and posts are untouched. Rules
-- (linked PAGE area only, a topic allowed for the area's type) are service rules, not constraints here.
CREATE TABLE content_work_nodes (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 page_id BIGINT NOT NULL REFERENCES site_pages(id) ON DELETE CASCADE,
 name VARCHAR(80) NOT NULL,
 topic_id BIGINT REFERENCES topics(id),
 sort_order INTEGER NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX content_work_node_page ON content_work_nodes(page_id,sort_order);
