-- The never-applied V4__navigation draft is archived outside the classpath.
-- Additive schema only: no IA, category conversion, content or publication creation.
CREATE TABLE content_types (
 code VARCHAR(32) PRIMARY KEY, name VARCHAR(80) NOT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE cohorts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(80) NOT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE topics (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(80) NOT NULL,
 description VARCHAR(500) NOT NULL DEFAULT '', active BOOLEAN NOT NULL DEFAULT TRUE,
 sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE content_type_topics (
 type_code VARCHAR(32) NOT NULL REFERENCES content_types(code),
 topic_id BIGINT NOT NULL REFERENCES topics(id), PRIMARY KEY(type_code,topic_id)
);
ALTER TABLE posts ADD COLUMN content_type_code VARCHAR(32) REFERENCES content_types(code);
ALTER TABLE post_publications ADD COLUMN content_type_code VARCHAR(32) REFERENCES content_types(code);
ALTER TABLE post_publications ADD COLUMN type_name_snapshot VARCHAR(80);
CREATE TABLE post_cohorts (
 post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
 cohort_id BIGINT NOT NULL REFERENCES cohorts(id), PRIMARY KEY(post_id,cohort_id)
);
CREATE TABLE post_topics (
 post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
 topic_id BIGINT NOT NULL REFERENCES topics(id), PRIMARY KEY(post_id,topic_id)
);
CREATE TABLE post_publication_cohorts (
 post_id BIGINT NOT NULL REFERENCES post_publications(post_id) ON DELETE CASCADE,
 cohort_id BIGINT NOT NULL REFERENCES cohorts(id), name_snapshot VARCHAR(80) NOT NULL,
 PRIMARY KEY(post_id,cohort_id)
);
CREATE TABLE post_publication_topics (
 post_id BIGINT NOT NULL REFERENCES post_publications(post_id) ON DELETE CASCADE,
 topic_id BIGINT NOT NULL REFERENCES topics(id), name_snapshot VARCHAR(80) NOT NULL,
 PRIMARY KEY(post_id,topic_id)
);
CREATE INDEX post_cohorts_lookup ON post_cohorts(cohort_id,post_id);
CREATE INDEX post_topics_lookup ON post_topics(topic_id,post_id);
CREATE INDEX published_cohorts_lookup ON post_publication_cohorts(cohort_id,post_id);
CREATE INDEX published_topics_lookup ON post_publication_topics(topic_id,post_id);
CREATE INDEX post_type_lookup ON posts(content_type_code,id);
CREATE INDEX published_type_lookup ON post_publications(content_type_code,post_id);
