-- Copy-only verification. No page/content/IA seed or existing data conversion.
CREATE TABLE page_templates (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(150) NOT NULL,
 description VARCHAR(1000) NOT NULL DEFAULT '',
 active BOOLEAN NOT NULL DEFAULT TRUE,
 blocks_json CLOB NOT NULL,
 revision BIGINT NOT NULL DEFAULT 0,
 created_by BIGINT NOT NULL REFERENCES users(id),
 updated_by BIGINT NOT NULL REFERENCES users(id),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
