import {useCallback,useEffect,useState} from 'react';
import {date} from './ui';
import {get,send,getClassifications} from './api';
import type {TemplateSummary,TemplateDocument,PreparedTemplate,Section,SelectedPost,Category,ClassificationCatalog} from './types';
import type {TemplateMode} from './templateBlocks';
import {BlockDialog} from './BlockDialog';
import './page-templates.css';
import {blockLabel,variationLabel} from './pagePresentation';
import {VersionHistoryDialog} from './VersionHistoryDialog';
import {initialHistoryVersion} from './versionHistory';

import {useEditorGuard,type EditorGuard,type GuardRegistration} from './editorGuard';
const base='/page-templates';
const states:Record<SelectedPost['status'],string>={PUBLISHED:'발행',UNPUBLISHED:'미발행',PRIVATE:'비공개',DELETED:'삭제됨',UNAVAILABLE:'사용 불가'};
export function TemplateContents({document,categories=[]}:{document:Pick<TemplateDocument,'blocks'|'references'>;categories?:Category[]}) {
 const [catalog,setCatalog]=useState<ClassificationCatalog|null>(null);
 useEffect(()=>{const c=new AbortController();void getClassifications(c.signal).then(setCatalog).catch(()=>{});return()=>c.abort();},[]);
 const terms=(ids:number[],kind:'cohorts'|'topics')=>ids.length?ids.map(id=>catalog?.[kind].find(t=>t.id===id)?.name||'분류 확인 중').join(', '):'전체';
 return <div className="template-contents"><h3>구성 미리보기 · {document.blocks.length}개 블록</h3>{!document.blocks.length&&<p>빈 구성</p>}<ol>{document.blocks.map((b,i)=><li key={i}><strong>{b.heading||blockLabel(b.type)}</strong><span>{blockLabel(b.type)} · {variationLabel(b.variation)} · {b.visible?'표시':'숨김'}</span>{b.body&&<p>{b.body.slice(0,180)}</p>}{b.imageId&&<p>이미지 #{b.imageId}</p>}{b.type==='POSTS'&&<p>{b.sourceMode==='manual'?'직접 선택 · '+(b.manual?.postIds.length??0)+'개 콘텐츠 · 지정 순서':b.sourceMode==='query'?'조건: '+(catalog?.types.find(t=>t.code===b.query?.typeCode)?.name||b.query?.typeCode)+' · 기수 '+terms(b.query?.cohortIds??[],'cohorts')+' · 주제 '+terms(b.query?.topicIds??[],'topics')+' · 최신순 '+b.query?.limit+'개':'기존 카테고리: '+(b.categoryId?categories.find(c=>c.id===b.categoryId)?.name||'연결 확인 필요':'전체')}</p>}</li>)}</ol>{document.references.length>0&&<><h3>직접 선택 콘텐츠의 현재 상태</h3><ul className="template-references">{document.references.map(p=><li key={p.id}>{p.title} <small>#{p.id}</small><span className={p.status==='PUBLISHED'?'':'template-warning'}>{states[p.status]}</span></li>)}</ul><p className="muted">콘텐츠 ID 참조는 유지됩니다. 공개 결과에는 발행 가능한 콘텐츠만 표시됩니다.</p></>}</div>;
}

export function TemplatesPanel({active,version,categories,registerGuard}:{active:boolean;version:number;categories:Category[];registerGuard:(path:string,guard:EditorGuard|null)=>void}) {
 const [historyId,setHistoryId]=useState<number|null>(()=>initialHistoryVersion()?Number(new URLSearchParams(window.location.search).get('template'))||null:null),[historyBusy,setHistoryBusy]=useState(false),[historyPending,setHistoryPending]=useState(false);
 const [rows,setRows]=useState<TemplateSummary[]>([]),[error,setError]=useState(''),[revision,setRevision]=useState(0),[document,setDocument]=useState<TemplateDocument|null>(null),[busy,setBusy]=useState(false);
 const [name,setName]=useState(''),[description,setDescription]=useState(''),[enabled,setEnabled]=useState(true),[dialogError,setDialogError]=useState('');
 const dirty=!!document&&(name!==document.info.name||description!==document.info.description||enabled!==document.info.active);
 const onGuard=useCallback((guard:EditorGuard|null)=>registerGuard('/design/templates',guard),[registerGuard]);
 useEditorGuard(dirty||historyPending,busy||historyBusy,onGuard);
 const [discard,setDiscard]=useState(false);
 const [loading,setLoading]=useState(true),[query,setQuery]=useState(''),[state,setState]=useState('');
 const filteredRows=rows.filter(row=>(row.name+' '+row.description).toLowerCase().includes(query.toLowerCase())&&(!state||String(row.active)===state));
 const close=()=>{if(busy)return;if(dirty)setDiscard(true);else setDocument(null);};
 useEffect(()=>{if(!active)return;const c=new AbortController();setLoading(true);void get<TemplateSummary[]>(base,c.signal).then(r=>{setRows(r);setError('');}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[active,version,revision]);
 async function open(id:number){setBusy(true);try{const d=await get<TemplateDocument>(base+'/'+id);setDiscard(false);setDocument(d);setName(d.info.name);setDescription(d.info.description);setEnabled(d.info.active);setDialogError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){if(!document)return;setBusy(true);try{await send(base+'/'+document.info.id,'PUT',{saveIntent:'MANUAL_DRAFT',revision:document.info.revision,name,description,active:enabled});setDocument(null);setRevision(n=>n+1);}catch(e){setDialogError((e as Error).message);}finally{setBusy(false);}}
 return <section className="templates-workspace"><div className="editor-heading"><div><h1>공용 템플릿</h1><p className="target-caption">반복해서 사용할 페이지 구성을 관리합니다. 새 템플릿은 페이지 편집에서 현재 구성을 저장해 만듭니다.</p></div><div className="heading-actions"><button onClick={()=>setRevision(n=>n+1)}>새로고침</button></div></div><div className="card template-list"><div className="search-bar"><input aria-label="템플릿 검색" placeholder="이름·설명 검색" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="템플릿 상태" value={state} onChange={e=>setState(e.target.value)}><option value="">전체 상태</option><option value="true">사용 가능</option><option value="false">사용 중지</option></select><span>{filteredRows.length}개</span></div>{loading?<p className="empty-state" role="status">템플릿을 불러오는 중…</p>:error?<div className="template-load-error"><p className="error-box" role="alert">{error}</p><button onClick={()=>setRevision(n=>n+1)}>다시 불러오기</button></div>:<><table className="data-table"><thead><tr><th>템플릿 / 설명</th><th>블록 수</th><th>사용 상태</th><th>최근 수정 / 수정자</th><th>작업</th></tr></thead><tbody>{filteredRows.map(t=><tr key={t.id}><td><button className="text-link" disabled={busy} onClick={()=>void open(t.id)}>{t.name}</button><p>{t.description||'설명 없음'}</p></td><td>{t.blockCount}개</td><td><span className="scope-tag">{t.active?'사용 가능':'사용 중지'}</span></td><td>{date(t.updatedAt)}<small>{t.updaterName}</small></td><td><div className="page-row-actions"><button disabled={busy} onClick={()=>void open(t.id)}>상세·설정</button><button disabled={busy} onClick={()=>setHistoryId(t.id)}>버전 이력</button></div></td></tr>)}</tbody></table>{!filteredRows.length&&<p className="empty-state">{rows.length?'조건에 맞는 템플릿이 없습니다. 검색어나 상태를 바꿔보세요.':'등록된 템플릿이 없습니다. 페이지 편집에서 현재 구성을 템플릿으로 저장하세요.'}</p>}</>}</div><p className="muted page-list-note">템플릿은 페이지 구성의 복사본입니다. 템플릿을 변경하거나 사용 중지해도 이미 적용한 페이지는 바뀌지 않습니다.</p>
 {historyId&&<VersionHistoryDialog kind="page-templates" id={historyId} active={active} onClose={()=>setHistoryId(null)} onBusy={setHistoryBusy} onPending={setHistoryPending} onRestored={async()=>{setRevision(n=>n+1);setDocument(null);}}/>}
 {document&&<BlockDialog active={active} title="공용 템플릿 관리" onClose={close}>{discard&&<div role="alert" className="template-confirm"><p>저장하지 않은 템플릿 변경을 버리고 닫을까요?</p><button onClick={()=>setDiscard(false)}>계속 편집</button><button className="danger" onClick={()=>{setDiscard(false);setDocument(null);}}>변경 버리고 닫기</button></div>}<fieldset disabled={busy}><label>템플릿 이름<input value={name} maxLength={150} onChange={e=>setName(e.target.value)}/></label><label>설명<textarea value={description} maxLength={1000} onChange={e=>setDescription(e.target.value)}/></label><label className="template-check"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>페이지에서 불러오기 허용</label><p className="muted">사용 중지해도 이미 적용한 페이지는 유지됩니다.</p><p className="muted">생성: {document.info.creatorName} · {date(document.info.createdAt)}<br/>수정: {document.info.updaterName} · {date(document.info.updatedAt)}</p><TemplateContents document={document} categories={categories}/><p className="muted">블록 구성을 바꾸려면 페이지 편집에서 구성한 뒤 ‘현재 구성을 템플릿으로 저장’에서 기존 템플릿을 선택하세요.</p>{dialogError&&<p role="alert" className="error-box">{dialogError}</p>}<div className="dialog-actions"><button onClick={close}>취소</button><button className="primary" disabled={!name.trim()} onClick={()=>void save()}>변경사항 저장</button></div></fieldset></BlockDialog>}
 </section>;
}

export function PageTemplateDialog({kind,sections,categories,onClose,onApply,active,onGuard}:{active:boolean;onGuard:GuardRegistration;categories:Category[];kind:'load'|'save';sections:Section[];onClose:()=>void;onApply:(copies:Section[],mode:TemplateMode,expected:string)=>void}) {
 const [rows,setRows]=useState<TemplateSummary[]>([]),[selected,setSelected]=useState(''),[document,setDocument]=useState<TemplateDocument|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [name,setName]=useState(''),[description,setDescription]=useState(''),[mode,setMode]=useState<TemplateMode>('append'),[confirm,setConfirm]=useState(false);
 const dirty=kind==='save'&&(name!==(document?.info.name??'')||description!==(document?.info.description??'')||!!selected);
 useEditorGuard(dirty,busy,onGuard);
 const [discard,setDiscard]=useState(false);
 const close=()=>{if(busy)return;if(dirty)setDiscard(true);else onClose();};
 // Freeze the configuration being saved. The dialog previews exactly this copy.
 const [snapshot]=useState(()=>structuredClone(sections));
 useEffect(()=>{let canceled=false;void get<TemplateSummary[]>(base).then(r=>{if(!canceled)setRows(r);}).catch(e=>{if(!canceled)setError(e.message);}).finally(()=>{if(!canceled)setLoading(false);});return()=>{canceled=true;};},[]);
 useEffect(()=>{setDocument(null);setConfirm(false);setError('');if(!selected){setName('');setDescription('');return;}const c=new AbortController();setLoading(true);void get<TemplateDocument>(base+'/'+selected,c.signal).then(d=>{if(!c.signal.aborted){setDocument(d);setName(d.info.name);setDescription(d.info.description);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[selected]);
 async function save(){setBusy(true);setError('');try{await send(selected?base+'/'+selected:base,selected?'PUT':'POST',{saveIntent:'MANUAL_DRAFT',revision:document?.info.revision,name,description,active:document?.info.active??true,blocks:snapshot});onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function apply(){if(!document)return;const expected=JSON.stringify(sections);setBusy(true);setError('');try{const result=await send<PreparedTemplate>(base+'/'+document.info.id+'/prepare','POST',{revision:document.info.revision});if(JSON.stringify(result.references)!==JSON.stringify(document.references)){setDocument({...document,references:result.references});setConfirm(false);setError('콘텐츠 상태가 변경되었습니다. 아래 상태를 확인한 뒤 다시 적용하세요.');return;}onApply(result.sections,mode,expected);onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const showing=kind==='save'?{blocks:snapshot,references:[]}:document;
 return <BlockDialog active={active} title={kind==='load'?'템플릿 불러오기':'현재 구성을 템플릿으로 저장'} onClose={close}>{discard&&<div role="alert" className="template-confirm"><p>저장하지 않은 템플릿 입력을 버리고 닫을까요?</p><button onClick={()=>setDiscard(false)}>계속 편집</button><button className="danger" onClick={onClose}>변경 버리고 닫기</button></div>}<fieldset disabled={busy}><label>{kind==='load'?'템플릿 선택':'저장 대상'}<select value={selected} disabled={loading} onChange={e=>setSelected(e.target.value)}><option value="">{kind==='load'?'선택하세요':'새 공용 템플릿'}</option>{rows.filter(t=>kind==='save'||t.active).map(t=><option key={t.id} value={t.id}>{t.name}{t.active?'':' · 사용 중지'}</option>)}</select></label>{loading&&<p role="status">불러오는 중…</p>}
 {kind==='save'&&<><label>템플릿 이름<input value={name} maxLength={150} onChange={e=>setName(e.target.value)}/></label><label>설명<textarea value={description} maxLength={1000} onChange={e=>setDescription(e.target.value)}/></label></>}
 {showing&&<TemplateContents document={showing} categories={categories}/>}
 {kind==='load'&&document&&<div className="template-application"><label>적용 방식<select value={mode} onChange={e=>{setMode(e.target.value as TemplateMode);setConfirm(false);}}><option value="append">현재 블록 뒤에 추가</option><option value="replace">현재 구성을 템플릿으로 교체</option></select></label><p><strong>{mode==='append'?`현재 ${sections.length}개 + 템플릿 ${document.blocks.length}개 = 총 ${sections.length+document.blocks.length}개 블록`:`현재 ${sections.length}개 블록을 템플릿 ${document.blocks.length}개 블록으로 교체`}</strong></p><p className="muted">{mode==='append'?'현재 블록을 유지하고 마지막에 새 블록을 추가합니다.':'현재 작성 중인 블록 구성을 모두 바꿉니다. 다음 단계에서 한 번 더 확인합니다.'} 공개본은 다시 게시할 때 바뀝니다.</p></div>}
 {confirm&&<div className="template-confirm" role="alert"><strong>{kind==='save'?'기존 템플릿 구성을 덮어쓸까요?':'현재 초안 블록을 교체할까요?'}</strong><p>{kind==='save'?'앞으로 불러올 구성만 바뀝니다. 이미 적용한 페이지는 바뀌지 않습니다.':'현재 초안 블록은 제거되고 템플릿 복사본으로 바뀝니다. 발행본은 다시 발행할 때 변경됩니다.'}</p></div>}
 {error&&<p role="alert" className="error-box">{error}</p>}<div className="dialog-actions"><button onClick={close}>취소</button>{kind==='save'?<button className="primary" disabled={loading||!name.trim()||!!selected&&!document} onClick={()=>{if(selected&&!confirm)setConfirm(true);else void save();}}>{selected?(confirm?'템플릿 구성 교체 저장':'기존 템플릿에 저장'):'새 템플릿 저장'}</button>:<button className="primary" disabled={loading||!document||!document.info.active||mode==='append'&&sections.length+(document?.blocks.length??0)>30} onClick={()=>{if(mode==='replace'&&!confirm)setConfirm(true);else void apply();}}>{mode==='replace'?(confirm?'확인하고 초안 교체':'교체 확인'):'초안 뒤에 추가'}</button>}</div>{kind==='load'&&document&&mode==='append'&&sections.length+document.blocks.length>30&&<p role="alert">추가하면 30개를 초과합니다. 블록을 줄이거나 교체를 선택하세요.</p>}</fieldset></BlockDialog>;
}
